language: php

php:
  - 5.5
  - 5.6

sudo: false

install:
  - bash install_phalcon.sh 2.0.9
  - composer update

script:
  - vendor/bin/codecept run unit --coverage --coverage-text

notifications:
  email:
    - sid@sidroberts.co.uk
