version: '3.6'

services:
  fpm:
    working_dir: /app
    hostname: php-fpm
    image: ${FPM_IMAGE}
    restart: unless-stopped
    volumes:
      - ../:/app
      - ./php/log/:/var/log/php7-fpm
      - ./php/app-config.ini:/usr/local/etc/php/conf.d/app-config.ini
      - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - TZ=${TZ}
      - COMPOSER_AUTH=${COMPOSER_AUTH}